### PR TITLE
fix visual elements on the frontpage

### PR DESCRIPTION
**Pull request by Majapur1**
- add small changes in alignment and element colors on the frontpage following the Sabina's comments

889fe95e1b013f911629874ed042da217ea01ac3

### CODE REVIEW

**Review by lkeegan — COMMENTED** [review]
@Majapur1 is it just the changes in https://github.com/ssciwr/mondey/commit/889fe95e1b013f911629874ed042da217ea01ac3 that you want to make here?

**Comment by Majapur1** [comment]
@lkeegan at that moment — yes. I met Sabina this week. She gave me additional comments and already approved the changes (including a new element) after reviewing them on my local machine.

You can merge this step, and I'll create another branch for the new ones.

**Comment by lkeegan** [comment]
Thanks - this can't be merged as is due to merge conflicts:
image
Maybe you could try to resolve these (a good skill to learn when working with git!), see e.g. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line

Otherwise let me know and I can extract that single commit and merge it.

**Comment by Majapur1** [comment]
@lkeegan thanks for this lesson! Now I understand how it works and why some changes cannot be just merged into `main`.

That was really helpful!

**Pull request merged**
